### ISSUE TITLE
The README suggestion for making more attractive

### ISSUE THREAD

**Issue by Nyconing** [JocysCom/JsClasses#4]
First, Your library is EPIC. 

I think this library is worth **more attention** and **more contributors**.

May you add in README:

- More attractive title and description. for example ".NET converted into JS", "Increasing inter-operability performances"
- Add simplified code comparing C# and JS, then emphasize the both return is identical. _Dont make it more than 3lines, or it might get ignored._
- Make it **a little bit** over-hyped. _(Dont look at me, Google, Microsoft, IBM all do this)_

You can put Jocys.com bigger at the top, and middle size of documentation.

**Comment by EJocys** [comment]
@Nyconing 
Thank you for useful suggestions. I will update README from my original article on CodeProject and maybe will try to overhype a little bit :).

**Comment by EJocys** [comment]
@Nyconing 
Thank you again. Updated main project title. Updated README with proper content and small example at the top. Hyped a *little bit* :).
