### ISSUE TITLE
Bug: System.Text.Debug

### ISSUE THREAD

**Issue by Nyconing** [JocysCom/JsClasses#5]
At line 719 
`bE = b1 << 18 | (b2 << 12)(b3 << 6) | b4;`

Error: Uncaught (in promise): TypeError: (b2 << 12) is not a function
TypeError: (b2 << 12) is not a function

**Comment by EJocys** [comment]
@Nyconing 
Thank you for reporting this bug. I've committed fix. You can do update to get latest changes.
